
language: go

sudo: enabled

os: linux

go:
  - 1.12.x

install: true

script:
  - env GO111MODULE=on go build cmd/contactsbook/main.go
  - env GO111MODULE=on go vet ./...
  - env GO111MODULE=on go test ./... -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
